@SecureAPI_HostAddress = https://localhost:44376/


GET {{SecureAPI_HostAddress}}/weatherforecast/
Accept:application/json
Authorization:Bearer CfDJ8Hjje2DGl5RNmjUQNHX_F9yPUavTqDCZmF4dEWDwAc0ICnd3zpJzdf4U-XeCbcG3TymKV1ucmuiiw3ArZcNBfYpULAq9dKeaYnpabJieaNqt_PKMGCEsZMUqinLnk2E5W5FFkAX6lF5qGwdSntXLhHqRdafncQLoZUOb-Y7WGgEgZlisfTOJam-9WxxQnkgCq8hwoHah9gqwmtbkLUP7SeUk25X5Vzi3n_njtxq4DqODX4oZqJq1iOfoojQthWV3pF9GT7Oy7eWMndv4F9Go7kqEohe8vywCGdx2fxxwZdMu1QLmjapFs-4LI9w6L-Ut1zAH9bXWfISojgoryKIKFLTJcUA_Cmrf-w9ZsaN969_lyje_y9pafJsaRtJr5Dj9tiucG3S7nv-x4KZrY-F_WvfB4iDjpgsLIsVSNaNfkddT9ixVN664pa-_akd1fCNH1DsTQnTLNhDXsJ1DR66MxWPfSGpUPo83C5SvjR60tbBaBZVBNkMIxY55iQRys3iRPs_70tR_oQCq-WaKo_4mHOmuzKMwokNYEGgPd5z0OV85710oP60VZmwlMvOn05FXpwsh-NUM-0CeuMAHKLucl-Vi4cZ53rXVXScPgVtF_L8c_yK1ClIUO8B-NxTd85KutebarpI-1zFo0_xPEHQ0gcuuozzvjKyq5yXTQ5HFMxDlI3Vd6g_T-TL9qLp3Ir7t-g
###
